apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: eqtl-api-logs
  namespace: eqtl
spec:
  storageClassName: standard-nfs-production
  accessModes:
    -  ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
