# Default values for sumstats-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ebispot/eqtl-sumstats-api
  tag: latest
  pullPolicy: Always
  containerPort: 8000
  logMountPath: "logs"
  dataMountPath: "/files/output"
  uid: 1000
  gid: 1000
  user: virtual_user

# Environment variables section
env: {}
  # These will be set at deployment time from GitLab variables

volume:
  log:
    ClaimName: eqtl-api-logs
  data:
    ClaimName: eqtl-data
    nfsServer: "<host name or IP>"
    path: "/path/to/files/"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  name: eqtl-rest-api
  type: NodePort
  port: 8000
  path: /eqtl/api(/|$)(.*)
  uvicornCmd: '["uvicorn", "sumstats.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1", "--limit-concurrency", "3"]'
  gunicornCmd: '["gunicorn", "--bind", "0.0.0.0:8000", "--worker-class=sync", "--workers=1", "--threads=2", "--max-requests=1000", "--max-requests-jitter=50", "--log-level=info", "--timeout=120", "--graceful-timeout=30", "--preload", "--access-logfile=-", "--error-logfile=-", "sumstats.main:app"]'


staticService:
  replicaCount: 1
  name: api-docs
  path: /api-docs
  type: NodePort
  port: 80
  image:
    repository: ebispot/eqtl-sumstats-docs
    tag: latest
    pullPolicy: Always
    containerPort: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: /eqtl/api(/|$)
      tls: []

k8Namespace: eqtl

# Adjusted resources to accommodate threading needs
resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: 100m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
