# Default values for sumstats-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Reduced number of replicas to decrease overall resource usage
replicaCount: 1

image:
  repository: ebispot/eqtl-sumstats-api
  tag: latest
  pullPolicy: Always
  containerPort: 8000
  logMountPath: "logs"
  dataMountPath: "/files/output"
  uid: 1000
  gid: 1000
  user: virtual_user

# Environment variables section
env: {}
  # MONGO_URI: "mongodb://localhost:27017"
  # DB_NAME: "eqtl_db"
  # ENVIRONMENT: "development"

volume:
  log:
    ClaimName: eqtl-api-logs
  data:
    ClaimName: eqtl-data
    nfsServer: "<host name or IP>"
    path: "/path/to/files/"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  name: eqtl-rest-api
  type: NodePort
  port: 8000
  path: /eqtl/api(/|$)(.*)
  uvicornCmd: '["uvicorn", "sumstats.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1", "--limit-concurrency", "3", "--timeout-keep-alive", "300", "--log-level=info"]'
  # Keep Gunicorn command for future reference
  gunicornCmd: '["gunicorn", "sumstats.main:app", "--bind", "0.0.0.0:8000", "--workers", "1", "--threads", "4", "--worker-class=sync", "--log-level=debug", "--timeout", "300"]'

staticService:
  replicaCount: 1
  name: api-docs
  path: /api-docs
  type: NodePort
  port: 80
  image:
    repository: ebispot/eqtl-sumstats-docs
    tag: latest
    pullPolicy: Always
    containerPort: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: /eqtl/api(/|$)
      tls: []

k8Namespace: eqtl

# Adjusted resources to accommodate threading needs
resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: 100m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
